### ISSUE TITLE
Labels are currently hard coded

### ISSUE THREAD

**Issue by bw4sz** [weecology/DeepForest-pytorch#2]
in dataset.py, need a read_classes() method take in a dict of classes either from file or as an arg. Everything is just hard coded as tree.

**Comment by dwaipayan05** [comment]
Hi @bw4sz, I was trying to create a read_classes() method to take in a dict of classes from file or as an arg. I followed a bit of the implementation of original DeepForest. I have sent a PR for the same. But since I am new to the Pytorch implementation of DeepForest. Hence, I am afraid I might have done some stuff wrong. I am willing to make any changes requested to follow the correct path. I am here to learn. 

Thank You !

**Comment by bw4sz** [comment]
@dwaipayan05 nice to have you around, we welcome all help. Looking at the PR now.
