### ISSUE TITLE
Bad performance when training with new data.

### ISSUE THREAD

**Issue by kristiyan-hristov** [weecology/DeepForest-pytorch#81]
Dear developers,
I annotated my images and tried training on them last Tuesday (6th July) and I managed to obtain pretty good results. However when repeating the same process on 9th July (exactly the same code as on the 6th) I got completely different results - either some bounding boxes that does not make sense at all or just no predictions whatsoever. I supposed the issue was mine and checked both the code, the images and the environment and everything seems to be ok. So my question is - did you change the structure of the training of your baseline model (the use_release one) or could you give me some suggestions how to fix the issue. I am running the project on Colab. 
Thanks in advance!

Kristiyan

**Comment by bw4sz** [comment]
hello. please see the large message on the front of this repo. It has been moved to the main deepforest repo and exists on for older uses. It is difficult to know without seeing any code, but we can confident the release model didn't change. The release model is tied to github releases in this repo, which is why its called the 'release model'. There has been no change in several months. If you have further issues, please open an issue : https://github.com/Weecology/DeepForest

**Comment by kristiyan-hristov** [comment]
![image](https://user-images.githubusercontent.com/78650985/125413516-b0fce931-b202-47e8-9ff2-a1b6a01422fe.png)
![image](https://user-images.githubusercontent.com/78650985/125413287-718acc71-290d-4734-8863-3525b14656a2.png)
![image](https://user-images.githubusercontent.com/78650985/125413395-acc82d84-a2d4-49b1-a1b7-431fc0bbacc6.png)

This is how my code, data and result look like the image that I predict after training is the same one that I have annotated beforehand so I want to compare the baseline prediction to the prediction after training.
Can you give me some clue what might be wrong?

Thanks in advance!
